export const RESTART_DELAY_BY_REASON_MS: Record<string, number> = {
  normal_onend: 150,
  settings_change: 150,
  websocket_reconnect: 150,
  watchdog_stall: 750,
  session_cycle: 150,
  long_segment_flush: 150,
};

export const INSTANCE_DEFAULTS = {
  restartDelayByReasonMs: { ...RESTART_DELAY_BY_REASON_MS },
  initialNoSpeechDelayMs: 150,
  maxNoSpeechDelayMs: 5000,
  initialNetworkBackoffMs: 500,
  maxNetworkBackoffMs: 30000,
  watchdogIntervalMs: 1000,
  maxStoppingMs: 2000,
  visibleIdleRestartMs: 30000,
  hiddenIdleRestartMs: 60000,
  stallDegradedAfterMs: 6000,
  micSilentDegradedAfterMs: 5000,
  recentMicActivityWindowMs: 2000,
  minimumReconnectIntervalMs: 500,
  maxBrowserSessionAgeMs: 180000,
  prepareCycleBeforeMs: 30000,
  voiceBelowRecognitionRmsThreshold: 0.025,
  voiceBelowRecognitionGraceMs: 8000,
  voiceBelowRecognitionMicWindowMs: 2000,
  voiceBelowRecognitionMinNoSpeech: 1,
  networkPreflightBurstThreshold: 3,
  networkPreflightBurstWindowMs: 12000,
  networkPreflightTimeoutMs: 4000,
  networkPreflightCooldownMs: 30000,
  recognitionStartLogMinGapMs: 4200,
} as const;
